// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RscXCfQEyRQ2GrNCShvTsfBg-6nkUI0',
    appId: '1:243493938341:web:f25b6ffea6a4157352594c',
    messagingSenderId: '243493938341',
    projectId: 'termingo-eda09',
    authDomain: 'termingo-eda09.firebaseapp.com',
    storageBucket: 'termingo-eda09.firebasestorage.app',
    measurementId: 'G-5377JCVTBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVhrrclqIXG86PdovxP9Id0cziGhut70',
    appId: '1:243493938341:android:92ec25a9b30cd6ce52594c',
    messagingSenderId: '243493938341',
    projectId: 'termingo-eda09',
    storageBucket: 'termingo-eda09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNKxXAPnrMHl5TqdSIAYldYzs4vWw2HqM',
    appId: '1:243493938341:ios:345d02571fd7f16952594c',
    messagingSenderId: '243493938341',
    projectId: 'termingo-eda09',
    storageBucket: 'termingo-eda09.firebasestorage.app',
    iosBundleId: 'com.example.termingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNKxXAPnrMHl5TqdSIAYldYzs4vWw2HqM',
    appId: '1:243493938341:ios:345d02571fd7f16952594c',
    messagingSenderId: '243493938341',
    projectId: 'termingo-eda09',
    storageBucket: 'termingo-eda09.firebasestorage.app',
    iosBundleId: 'com.example.termingo',
  );
}
